### ISSUE TITLE
Gallery FC when share picture

### ISSUE THREAD

**Issue by ingbrzy** [redmaner/MIUI8-XML-DUTCH#121]
https://xiaomi.eu/community/threads/6-9-29.35401/page-13#post-325426

**Comment by ingbrzy** [comment]
`10-01 163001.902 10034 10034 E AndroidRuntime FATAL EXCEPTION main

10-01 163001.902 10034 10034 E AndroidRuntime Process com.miui.gallery, PID 10034

10-01 163001.902 10034 10034 E AndroidRuntime java.lang.IllegalArgumentException Unknown element format

10-01 163001.902 10034 10034 E AndroidRuntime   at java.text.MessageFormat.parseVariable(MessageFormat.java975)

10-01 163001.902 10034 10034 E AndroidRuntime   at java.text.MessageFormat.applyPattern(MessageFormat.java416)

10-01 163001.902 10034 10034 E AndroidRuntime   at java.text.MessageFormat.init(MessageFormat.java360)

10-01 163001.902 10034 10034 E AndroidRuntime   at java.text.MessageFormat.init(MessageFormat.java374)

10-01 163001.902 10034 10034 E AndroidRuntime   at java.text.MessageFormat.format(MessageFormat.java731)

10-01 163001.902 10034 10034 E AndroidRuntime   at com.miui.gallery.ui.PhotoPageFragmentBase$ChoiceManagerBase$2.run(PhotoPageFragmentBase.java)

10-01 163001.902 10034 10034 E AndroidRuntime   at android.os.Handler.handleCallback(Handler.java)

10-01 163001.902 10034 10034 E AndroidRuntime   at android.os.Handler.dispatchMessage(Handler.java)

10-01 163001.902 10034 10034 E AndroidRuntime   at android.os.Looper.loop(Looper.java)

10-01 163001.902 10034 10034 E AndroidRuntime   at android.app.ActivityThread.main(ActivityThread.java)

10-01 163001.902 10034 10034 E AndroidRuntime   at java.lang.reflect.Method.invoke(Native Method)

10-01 163001.902 10034 10034 E AndroidRuntime   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java)

10-01 163001.902 10034 10034 E AndroidRuntime   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java)`

**Comment by MannyRibo** [comment]
https://github.com/redmaner/MIUI8-XML-DUTCH/pull/123/commits/c7ac059fd5502e7a61e9fd1f60c6a8d9f5b506a6
