### ISSUE TITLE
MiRemote FC when opening

### ISSUE THREAD

**Issue by MannyRibo** [redmaner/MIUI8-XML-DUTCH#122]
10-01 19:09:46.338 21993 21993 E AndroidRuntime: FATAL EXCEPTION: main

10-01 19:09:46.338 21993 21993 E AndroidRuntime: Process: com.duokan.phone.remotecontroller, PID: 21993

10-01 19:09:46.338 21993 21993 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.duokan.phone.remotecontroller/com.xiaomi.mitv.phone.remotecontroller.HomeActivity}: java.lang.ArrayIndexOutOfBoundsException: length=5; index=5

10-01 19:09:46.338 21993 21993 E AndroidRuntime:    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java)

10-01 19:09:46.338 21993 21993 E AndroidRuntime:    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java)

10-01 19:09:46.338 21993 21993 E AndroidRuntime:    at android.app.ActivityThread.access$900(ActivityThread.java)

10-01 19:09:46.338 21993 21993 E AndroidRuntime:    at android.app.ActivityThread$H.handleMessage(ActivityThread.java)

10-01 19:09:46.338 21993 21993 E AndroidRuntime:    at android.os.Handler.dispatchMessage(Handler.java)

10-01 19:09:46.338 21993 21993 E AndroidRuntime:    at android.os.Looper.loop(Looper.java)

10-01 19:09:46.338 21993 21993 E AndroidRuntime:    at android.app.ActivityThread.main(ActivityThread.java)

10-01 19:09:46.338 21993 21993 E AndroidRuntime:    at java.lang.reflect.Method.invoke(Native Method)

10-01 19:09:46.338 21993 21993 E AndroidRuntime:    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java)

10-01 19:09:46.338 21993 21993 E AndroidRuntime:    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java)

10-01 19:09:46.338 21993 21993 E AndroidRuntime: Caused by: java.lang.ArrayIndexOutOfBoundsException: length=5; index=5

10-01 19:09:46.338 21993 21993 E AndroidRuntime:    at com.xiaomi.mitv.phone.remotecontroller.epg.q.o(Unknown Source)

10-01 19:09:46.338 21993 21993 E AndroidRuntime:    at com.xiaomi.mitv.phone.remotecontroller.epg.q.<init>(Unknown Source)

10-01 19:09:46.338 21993 21993 E AndroidRuntime:    at com.xiaomi.mitv.phone.remotecontroller.XMRCApplication.c(Unknown Source)

10-01 19:09:46.338 21993 21993 E AndroidRuntime:    at com.xiaomi.mitv.phone.remotecontroller.HomeActivity.onCreate(Unknown Source)

10-01 19:09:46.338 21993 21993 E AndroidRuntime:    at android.app.Activity.performCreate(Activity.java)

10-01 19:09:46.338 21993 21993 E AndroidRuntime:    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java)

**Comment by ingbrzy** [comment]
check yours arrays.xml 
https://github.com/redmaner/MIUI8-XML-DUTCH/blob/master/Dutch/main/XMRemoteController.apk/res/values-nl/arrays.xml
