### ISSUE TITLE
Wallpaper

### ISSUE THREAD

**Issue by suusdo** [redmaner/MIUI8-XML-DUTCH#131]
Als je via Instellingen naar Achtergrond gaat staat er vervolgens < Wallpaper.
 Succes.

**Comment by Cueie** [comment]
Kan je deze nog eens specifiek en exact hetzelde als wat er staat doorgeven.
Als je de tekst exact hetzelde meld is dit gemakkelijker om dit weer te vinden

**Comment by suusdo** [comment]
In mijn Redmi 3 (6.10.20) staat, als je via Instellingen naar Achtergrond gaat, bovenin het venster Wallpaper. Dit zou Achtergrond moeten zijn.
Succes

**Comment by suusdo** [comment]
Inmiddels met MIUI 8.2 6.11.24 | Beta, staat Wallpaper nog steeds op de pagina als je via Instellingen naar Achtergrond gaat.
