### ISSUE TITLE
Set default alarm sound

### ISSUE THREAD

**Issue by suusdo** [redmaner/MIUI8-XML-DUTCH#148]
Als je via Klok naar Instellingen gaat, staat er op de 2de regel Set default alarm sound. Dit zou vlgs mij Stel  geluid voor klokalarm in oid. Ga je naar Set default alarm sound dan staat er Beltonen vermeld op de kop van de pagina. Dit zou Geluid voor klokalarm oid moeten zijn.

**Comment by Cueie** [comment]
Weet het weer hebben nog maar vandaag terug de hele Repo gesynchroniseerd met de master Repo, daardoor zullen er wel wat dingen zijn die niet vertaald zijn. Pas vanaf volgende update zou de Repo volledig in orde moeten staan.
Bedankt voor u begrip
