### ISSUE TITLE
Vertaling schermvergrendeling

### ISSUE THREAD

**Issue by monsieurpaulu** [redmaner/MIUI8-XML-DUTCH#155]
Bij de laatste 2 roms mist de nl vertaling bij het scherm ontgrendelen.
![img_20161106_064752](https://cloud.githubusercontent.com/assets/7716225/20035644/5ab058be-a3ed-11e6-84b6-a938168378c5.jpg)

Verder ook bij de status bar
![img_20161106_100425](https://cloud.githubusercontent.com/assets/7716225/20036438/bc75b434-a408-11e6-871b-e845e6e53607.jpg)

En bij de foto gallerij zijn er helemaal geen nl vertalingen
![img_20161106_100532](https://cloud.githubusercontent.com/assets/7716225/20036440/ccb706b8-a408-11e6-8e1b-3cdeb624fac8.jpg)

Mi4c

**Comment by MannyRibo** [comment]
De slide up to unlock is weer vertaald, samen met de tekst in de zoekbalk. Met de galerij is er waarschijnlijk wat anders aan de hand want de dingen die onvertaald zijn op jouw screenshot zijn gewoon vertaald in de repo. Waarom de datumnotatie overal zo staat moet ik even naar kijken.
Dankjewel.

**Comment by monsieurpaulu** [comment]
De hele gallerij app is Engels waarschijnlijk vandaar ook dat de datumnotatie.
Zit echt geen 1 woord nl in .

Alvast bedankt voor de rest !

**Comment by monsieurpaulu** [comment]
De genoemde punten lijken opgelost .

Bedankt !!
