### ISSUE TITLE
Wrong variables

### ISSUE THREAD

**Issue by ingbrzy** [redmaner/MIUI8-XML-DUTCH#16]
See a report http://dpaste.com/2KDQD15

search for "MNPS mismatch" in these files https://mega.nz/#!ysYXlYJK!F9olxuxDD5mJU9H4c8iFzyqNAOWTW4hSGaHm-0vW5xY

**Comment by ingbrzy** [comment]
Can cause issue #15

**Comment by redmaner** [comment]
I'll look into this tomorrow
