### ISSUE TITLE
"Galerij is gestopt." melding bij verzenden van foto vanuit galerij naar bv Whatsapp

### ISSUE THREAD

**Issue by drabbeltje** [redmaner/MIUI8-XML-DUTCH#189]
Ik weet niet zeker of het met de vertaling te maken heeft, maar op mijn MI4s krijg ik elke keer als ik een foto wil verzenden vanuit de galerij de melding "Galerij is gestopt." Ik kan de foto daarna wel gewoon verzenden maar het is toch wel vrij irritant. Dit is al minstens 2 weekly releases zo (zit nu op 6.12.22). Een collega met een MI4c heeft hetzelfde probleem.

**Comment by redmaner** [comment]
@ingbrzy: Issue causes gallery to stop when sending a photo, could this be a translation issue?

**Comment by ingbrzy** [comment]
yes.. post log here...

**Comment by redmaner** [comment]
Thanks
