### ISSUE TITLE
verkeerde vertaling naar verwijzing email app

### ISSUE THREAD

**Issue by jo47** [redmaner/MIUI8-XML-DUTCH#233]
na een update naar 7.4.20 werkte mijn mail box niet meer,op het scherm verscheen dat ik de systeem app moest recetten,moet zijn de geïnstalleerde app

**Comment by MannyRibo** [comment]
Weet je exact wat deze zin was die niet goed is vertaald? Ik kan het zo niet opzoeken. Was dit de standaard e-mailapp of een andere die je zelf hebt geïnstalleerd?

**Comment by jo47** [comment]
Het is de standaard app.
Ik had een update gedaan naar een nieuwere rom,na opstarten wilde ik mail openen, dat ging niet,toen kreeg ik op het scherm te zien:ga naar instellingen /systeem mail app en verwijder en verwijder cache (dat weet ik niet exact) ik weet wel dat ik gegaan ben naar de systeem app,maar daar kon ik niets mee, toen naar de geïnstalleerde  app en daar alles verwijderd toen kon ik de accounts weer instellen.
Dus de verwijzing was niet correct.

Groet Jo Vos Druten



Verzonden vanuit Mail voor Windows 10

Van: Manny
Verzonden: zaterdag 29 april 2017 15:18
Aan: redmaner/MIUI8-XML-DUTCH
CC: jo47; Author
Onderwerp: Re: [redmaner/MIUI8-XML-DUTCH] verkeerde vertaling naar verwijzingemail app (#233)

Weet je exact wat deze zin was die niet goed is vertaald? Ik kan het zo niet opzoeken. Was dit de standaard e-mailapp of een andere die je zelf hebt geïnstalleerd?

**Comment by MannyRibo** [comment]
Dan gaat het waarschijnlijk om de volgende zin? 

<string name="get_database_exception">"Wis de gegevens van deze app in Instellingen &gt; Systeemapps en probeer het opnieuw"</string>

Dit staat origineel in het Engels ook vertaald als system app dus is eigenlijk een fout die er standaard inzit. Dan zal ik het bij deze veranderen, dankjewel voor het melden.

**Comment by jo47** [comment]
Oke dank jullie ook

Verzonden vanuit Mail voor Windows 10

Van: Manny
Verzonden: donderdag 4 mei 2017 15:03
Aan: redmaner/MIUI8-XML-DUTCH
CC: jo47; Author
Onderwerp: Re: [redmaner/MIUI8-XML-DUTCH] verkeerde vertaling naar verwijzingemail app (#233)

Dan gaat het waarschijnlijk om de volgende zin?
"Wis de gegevens van deze app in Instellingen > Systeemapps en probeer het opnieuw"
Dit staat origineel in het Engels ook vertaald als system app dus is eigenlijk een fout die er standaard inzit. Dan zal ik het bij deze veranderen, dankjewel voor het melden.
