### ISSUE TITLE
[nikel] Gekke Tekst Data Gebruik

### ISSUE THREAD

**Issue by EMPool** [redmaner/MIUI8-XML-DUTCH#250]
in de nederlandse vertaling zit bij de "schuif balken" een soort html opmaak ipv de juiste tekst.
in de engelse taal werkt het wel (zie 2de link (english)).

ik zie dit op mijn redmi note 4 mtk 64gb 4gb ram

ik draai firmware  weekly MIUI 8.3 7.5.25

![dutch](https://cloud.githubusercontent.com/assets/29087087/26618700/8c582c3a-45db-11e7-80b1-f251f5926248.png)
![english](https://cloud.githubusercontent.com/assets/29087087/26618701/8c5a817e-45db-11e7-96e6-d8edf63e954c.png)

**Comment by MannyRibo** [comment]
Dankjewel, ik zal er later vanavond naar kijken.
