### ISSUE TITLE
Vertaling weer app

### ISSUE THREAD

**Issue by monsieurpaulu** [redmaner/MIUI8-XML-DUTCH#261]
De weer app mist de laatste 3 versies op de mi5s een vertaling.
Zie foto's
![screenshot_2017-07-22-09-42-40-069_com miui weather2](https://user-images.githubusercontent.com/7716225/28489351-7bdb613c-6ec2-11e7-92f2-5091147ef3b7.png)
![screenshot_2017-07-22-09-42-46-091_com miui weather2](https://user-images.githubusercontent.com/7716225/28489352-7bddb1ee-6ec2-11e7-80bc-d97a9b66ed15.png)

**Comment by Cueie** [comment]
Wordt aan gewerkt

**Comment by monsieurpaulu** [comment]
Helemaal top !
